# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowRev01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.setting = QtWidgets.QPushButton(Form)
        self.setting.setMaximumSize(QtCore.QSize(30, 30))
        self.setting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logo settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting.setIcon(icon)
        self.setting.setObjectName("setting")
        self.horizontalLayout_2.addWidget(self.setting)
        self.help = QtWidgets.QPushButton(Form)
        self.help.setMaximumSize(QtCore.QSize(30, 30))
        self.help.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.help.setObjectName("help")
        self.horizontalLayout_2.addWidget(self.help)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pilihExcel = QtWidgets.QLabel(Form)
        self.pilihExcel.setMinimumSize(QtCore.QSize(100, 200))
        self.pilihExcel.setStyleSheet("border: 1px dashed")
        self.pilihExcel.setText("")
        self.pilihExcel.setPixmap(QtGui.QPixmap("../logo excel 20% size.png"))
        self.pilihExcel.setAlignment(QtCore.Qt.AlignCenter)
        self.pilihExcel.setObjectName("pilihExcel")
        self.verticalLayout_2.addWidget(self.pilihExcel)
        self.mulai = QtWidgets.QPushButton(Form)
        self.mulai.setStyleSheet("background-color: rgb(0, 177, 0);\n"
"color: rgb(255, 255, 255);")
        self.mulai.setObjectName("mulai")
        self.verticalLayout_2.addWidget(self.mulai)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.help.setText(_translate("Form", "?"))
        self.mulai.setText(_translate("Form", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
